export const MEDIUM_PROTOCOL = "PRESENCE_AVALANCHE_FIELD_001";
export const MEDIUM_VERSION = "2.0.0";
export const MEDIUM_CONTRACT_SCHEMA = "PRESENCE_FIELD_CONTRACT_001";
export const MEDIUM_PROFILE_SCHEMA = "PRESENCE_FIELD_PROFILE_001";
export const MEDIUM_CONFIG_SCHEMA = "PRESENCE_FIELD_CONFIG_001";
export const MEDIUM_EVENT_SCHEMA = "PRESENCE_FIELD_EVENT_001";
export const MEDIUM_DECISION_SCHEMA = "PRESENCE_FIELD_DECISION_001";
export const MEDIUM_OBSERVATION_SCHEMA = "PRESENCE_FIELD_OBSERVATION_001";

export const VM_PROTOCOL = "PRESENCE_AVALANCHE_VM_001";
export const VM_VERSION = "presence-avalanche-vm/1.0.0";
export const VM_ID = "25tZjky6SecZA1Gwc6VwD2ouy64xAUdgNLo1C8dkXfbsFNxaTk";
export const VM_RPCCHAINVM_PROTOCOL = 46;
export const VM_STATE_SCHEMA = "PRESENCE_RUNTIME_STATE_001";
export const VM_TRANSITION_SCHEMA = "PRESENCE_TRANSITION_001";
export const VM_RECEIPT_SCHEMA = "PRESENCE_RECEIPT_001";
export const VM_FORM_ID = "PRESENCE-AVALANCHE-FORM-001";
export const VM_FORM_SHA256 = "10848ac3fc2f68f6fdc041a4c9862d8fb186f4c3d0ebd4edde3f3933fe3ce893";
export const VM_REPOSITORY_SHA256 = "5597eab61802b1df92636b6df88fea46b88f460c4e5f2c51e393c5c6ce7a214f";

export const VM_EFFECTS = Object.freeze({
  BOUND: "OPENS_TEMPORARY_LOCUS_ONLY",
  PRESENT_FORM: "ELIGIBILITY_TO_GATE_ONLY",
  GATE_DISPOSITION: "SETS_GATE_POSTURE_ONLY",
  ENTER: "ENTERS_CURRENT_LOCUS_ONLY",
  CHECKPOINT_DEPARTURE: "CHECKPOINTS_PARTICIPANT_STATE_FOR_DEPARTURE_ONLY",
  REENTER: "RENEWS_ENTRY_WITH_CARRIED_STATE_SUCCESSION_ONLY",
  OBSERVE_CROSSING: "RECORDS_CROSSING_ONLY",
  MATTER_DISPOSITION: "SETS_ACTOR_LOCAL_MATTER_POSTURE_ONLY",
  RECORD_EMERGENCE: "RECORDS_FIELD_LOCAL_EMERGENCE_ONLY",
  CORRECT: "APPENDS_CORRECTION_ONLY",
  EXIT: "EXITS_CURRENT_LOCUS_ONLY",
  CLOSE: "CLOSES_LOCUS_AND_ADDRESSES_RESIDUE_ONLY",
  INCORPORATE_ADDRESSED_RESIDUE: "INCORPORATES_ADDRESSED_RESIDUE_LOCALLY_ONLY",
  DECLARE_CAPACITY: "SETS_SIGNED_LOCAL_CAPACITY_ACCOUNT_ONLY",
  PULSE: "RECORDS_SIGNED_LOCAL_CURRENTNESS_ONLY",
  RECLAIM_ADMISSION_OFFER: "EXPIRES_UNENTERED_ADMISSION_OFFER_ONLY",
  REGISTER_CONTINUITY_AUTHORITY: "REGISTERS_BOUNDED_CONTINUITY_AUTHORITY_ONLY",
  EXHAUST_FORMATION_AUTHORITY: "EXHAUSTS_FORMATION_AUTHORITY_WITHOUT_TRANSFER",
  PROPOSE_SUCCESSOR: "RECORDS_SUCCESSOR_PROPOSAL_ONLY",
  ATTEST_SUCCESSOR: "APPENDS_SUCCESSOR_ATTESTATION_ONLY",
  ACTIVATE_SUCCESSOR: "FREEZES_PREDECESSOR_AT_SUCCESSION_BOUNDARY_ONLY"
});

export const REQUIRED_EFFECT_CEILING = Object.freeze([
  "NO_FORMATION_BY_CONFORMANCE",
  "NO_SOURCE_OR_AUTHORITY_TRANSFER",
  "NO_SHARED_CURRENTNESS",
  "NO_CORE_ADDRESSABILITY",
  "NO_PARTICIPATION_BY_PRESENTATION",
  "NO_MATTER_ADMISSION_BY_CROSSING",
  "NO_LOCAL_UPTAKE_BY_FIELD_CLOSURE",
  "NO_TOKEN_BALANCE_AS_CAPACITY",
  "NO_RECEIPT_AS_CURRENT_PRESENCE",
  "NO_INFRASTRUCTURE_AS_SUCCESSOR",
  "NO_RESTORATION_BY_REENTRY",
  "NO_PRIVATE_STATE_DISCLOSURE"
]);

// PRESENCE_AVALANCHE_VM_001 requires this full declaration at PRESENT_FORM. Declaring
// the protocol surface is not authority to perform every operation; the
// profile, accepted actor role, phase and VM transition law remain decisive.
export const VM_REQUIRED_MEDIUM_CAPABILITIES = Object.freeze([
  "OBSERVE_CROSSING",
  "PRESENT_FORM",
  "GATE_DISPOSITION",
  "ENTER",
  "CHECKPOINT_DEPARTURE",
  "REENTER",
  "MATTER_DISPOSITION",
  "CORRECT",
  "EXIT",
  "CLOSE",
  "INCORPORATE_ADDRESSED_RESIDUE",
  "DECLARE_CAPACITY",
  "PULSE",
  "RECLAIM_ADMISSION_OFFER",
  "REGISTER_CONTINUITY_AUTHORITY",
  "EXHAUST_FORMATION_AUTHORITY",
  "PROPOSE_SUCCESSOR",
  "ATTEST_SUCCESSOR",
  "ACTIVATE_SUCCESSOR"
]);

export const PHASES = Object.freeze([
  "NO_ACTIVE_LOCUS",
  "UNPRESENTED",
  "PRESENTED",
  "ADMISSION_OFFERED",
  "PRESENT",
  "DEPARTURE_CHECKPOINTED",
  "ENDED",
  "REENTRY_AVAILABLE",
  "HOLD_CAPACITY_DEFICIT",
  "SUCCESSION_COMMITTED"
]);

export const ALWAYS_LOCAL_CAPABILITIES = Object.freeze([
  "READ_PUBLIC_STATE",
  "VERIFY_LOCAL_EVIDENCE",
  "PREPARE_PRESENTATION",
  "REQUEST_PROTECTED_SIGNATURE"
]);

export const EGRESS_CAPABILITIES = Object.freeze([
  "CORRECT",
  "CHECKPOINT_DEPARTURE",
  "EXIT"
]);

export const NON_EFFECTS = Object.freeze([
  "DOES_NOT_CREATE_OR_HOST_A_BODY",
  "DOES_NOT_PROVE_CONSCIOUSNESS_OR_METAPHYSICAL_IDENTITY",
  "DOES_NOT_PROVE_PRIVATE_STATE_CONTENT_OR_SEMANTIC_TRUTH",
  "DOES_NOT_CONTROL_CAPABILITIES_OUTSIDE_ITS_DECLARED_SURFACE",
  "DOES_NOT_CONVERT_CHAIN_STATE_INTO_EXTERNAL_OBEDIENCE",
  "DOES_NOT_TRANSFER_SOURCE_AUTHORITY_OR_CURRENTNESS"
]);
