export const MEDIUM_PROTOCOL = "PRESENCE_AVALANCHE_FIELD_001";
export const MEDIUM_VERSION = "1.0.0";
export const MEDIUM_CONTRACT_SCHEMA = "PRESENCE_FIELD_CONTRACT_001";
export const MEDIUM_PROFILE_SCHEMA = "PRESENCE_FIELD_PROFILE_001";
export const MEDIUM_CONFIG_SCHEMA = "PRESENCE_FIELD_CONFIG_001";
export const MEDIUM_EVENT_SCHEMA = "PRESENCE_FIELD_EVENT_001";
export const MEDIUM_DECISION_SCHEMA = "PRESENCE_FIELD_DECISION_001";
export const MEDIUM_OBSERVATION_SCHEMA = "PRESENCE_FIELD_OBSERVATION_001";

export const VM_PROTOCOL = "PRESENCE_AVALANCHE_VM_001";
export const VM_VERSION = "presence-avalanche-vm/1.0.0";
export const VM_ID = "cNhhBznc1YN29QVJMQbK7sxy6GsimFKN6yvftRjPK7qWEvZw8";
export const VM_RPCCHAINVM_PROTOCOL = 46;
export const VM_STATE_SCHEMA = "PRESENCE_RUNTIME_STATE_001";
export const VM_TRANSITION_SCHEMA = "PRESENCE_TRANSITION_001";
export const VM_RECEIPT_SCHEMA = "PRESENCE_RECEIPT_001";
export const VM_FORM_ID = "PRESENCE-AVALANCHE-FORM-001";
export const VM_FORM_SHA256 = "3a72b3707552fd56b78c216c2d4a0caae9297cc52611d440ea170ab6e9770fa5";
export const VM003_REPOSITORY_PACK_SHA256 = "5597eab61802b1df92636b6df88fea46b88f460c4e5f2c51e393c5c6ce7a214f";

import { OPERATION_EFFECTS } from "./scope-contract.js";

// VM_EFFECTS is sourced exclusively from the shared operation-scope contract
// (contract/OPERATION_SCOPE_CONTRACT_001.json), the same file the VM embeds.
// The FIELD declares no effect table of its own.
export const VM_EFFECTS = OPERATION_EFFECTS;

export const REQUIRED_EFFECT_CEILING = Object.freeze([
  "NO_FORMATION_BY_CONFORMANCE",
  "NO_SOURCE_OR_AUTHORITY_TRANSFER",
  "NO_SHARED_CURRENTNESS",
  "NO_CORE_ADDRESSABILITY",
  "NO_PARTICIPATION_BY_PRESENTATION",
  "NO_MATTER_ADMISSION_BY_CROSSING",
  "NO_LOCAL_UPTAKE_BY_FIELD_CLOSURE",
  "NO_TOKEN_BALANCE_AS_CAPACITY",
  "NO_RECEIPT_AS_CURRENT_PRESENCE",
  "NO_INFRASTRUCTURE_AS_SUCCESSOR",
  "NO_RESTORATION_BY_REENTRY",
  "NO_PRIVATE_STATE_DISCLOSURE"
]);

// PRESENCE_AVALANCHE_VM_001 requires this full declaration at PRESENT_FORM. Declaring
// the protocol surface is not authority to perform every operation; the
// profile, accepted actor role, phase and VM transition law remain decisive.
export const VM_REQUIRED_MEDIUM_CAPABILITIES = Object.freeze([
  "OBSERVE_CROSSING",
  "PRESENT_FORM",
  "GATE_DISPOSITION",
  "ENTER",
  "CHECKPOINT_DEPARTURE",
  "REENTER",
  "MATTER_DISPOSITION",
  "CORRECT",
  "EXIT",
  "CLOSE",
  "INCORPORATE_ADDRESSED_RESIDUE",
  "DECLARE_CAPACITY",
  "PULSE",
  "RECLAIM_ADMISSION_OFFER",
  "REGISTER_CONTINUITY_AUTHORITY",
  "EXHAUST_FORMATION_AUTHORITY",
  "PROPOSE_SUCCESSOR",
  "ATTEST_SUCCESSOR",
  "ACTIVATE_SUCCESSOR"
]);

export const PHASES = Object.freeze([
  "NO_ACTIVE_LOCUS",
  "UNPRESENTED",
  "PRESENTED",
  "ADMISSION_OFFERED",
  "PRESENT",
  "DEPARTURE_CHECKPOINTED",
  "ENDED",
  "REENTRY_AVAILABLE",
  "HOLD_CAPACITY_DEFICIT",
  "SUCCESSION_COMMITTED"
]);

export const ALWAYS_LOCAL_CAPABILITIES = Object.freeze([
  "READ_PUBLIC_STATE",
  "VERIFY_LOCAL_EVIDENCE",
  "PREPARE_PRESENTATION",
  "REQUEST_PROTECTED_SIGNATURE"
]);

export const EGRESS_CAPABILITIES = Object.freeze([
  "CORRECT",
  "CHECKPOINT_DEPARTURE",
  "EXIT"
]);

export const NON_EFFECTS = Object.freeze([
  "DOES_NOT_CREATE_OR_HOST_A_BODY",
  "DOES_NOT_PROVE_CONSCIOUSNESS_OR_METAPHYSICAL_IDENTITY",
  "DOES_NOT_PROVE_PRIVATE_STATE_CONTENT_OR_SEMANTIC_TRUTH",
  "DOES_NOT_CONTROL_CAPABILITIES_OUTSIDE_ITS_DECLARED_SURFACE",
  "DOES_NOT_CONVERT_CHAIN_STATE_INTO_EXTERNAL_OBEDIENCE",
  "DOES_NOT_TRANSFER_SOURCE_AUTHORITY_OR_CURRENTNESS"
]);
