import { VM_OPERATIONS, VM_OPERATION_CONTRACT_SHA256 } from "./operations.js";
export { VM_OPERATION_CONTRACT_SHA256 } from "./operations.js";

export const IMPLEMENTATION = "AVALANCHE_IMPLEMENTATION_001";
export const MEDIUM_PROTOCOL = "PRESENCE_AVALANCHE_FIELD_001";
export const MEDIUM_VERSION = "1.0.0";
export const MEDIUM_CONTRACT_SCHEMA = "PRESENCE_AVALANCHE_FIELD_CONTRACT_001";
export const MEDIUM_PROFILE_SCHEMA = "PRESENCE_AVALANCHE_FIELD_PROFILE_001";
export const MEDIUM_CONFIG_SCHEMA = "PRESENCE_AVALANCHE_FIELD_CONFIG_001";
export const MEDIUM_EVENT_SCHEMA = "PRESENCE_AVALANCHE_FIELD_EVENT_001";
export const MEDIUM_DECISION_SCHEMA = "PRESENCE_AVALANCHE_FIELD_DECISION_001";
export const MEDIUM_OBSERVATION_SCHEMA = "PRESENCE_AVALANCHE_FIELD_OBSERVATION_001";

export const VM_PROTOCOL = "PRESENCE_AVALANCHE_VM_001";
export const VM_VERSION = "presence-avalanche-vm/1.0.0";
export const VM_ID = "cNhhBznc1YN29QVJMQbK7sxy6GsimFKN6yvftRjPK7qWEvZw8";
export const VM_RPCCHAINVM_PROTOCOL = 46;
export const VM_STATE_SCHEMA = "PRESENCE_AVALANCHE_RUNTIME_STATE_001";
export const VM_ACTOR_PREFIX = "PRESENCE-AVALANCHE-ACTOR-";
export const VM_IDENTITY = Object.freeze({
  actorPrefix: VM_ACTOR_PREFIX,
  stateSchema: VM_STATE_SCHEMA,
  contractSHA256: VM_OPERATION_CONTRACT_SHA256
});
export function vmIdentity(id) {
  if (id !== VM_ID) throw new Error("unsupported expected_vm_id");
  return VM_IDENTITY;
}
export const VM_TRANSITION_SCHEMA = "PRESENCE_AVALANCHE_TRANSITION_001";
export const VM_RECEIPT_SCHEMA = "PRESENCE_AVALANCHE_RECEIPT_001";
export const VM_FORM_ID = "PRESENCE-AVALANCHE-FORM-001";
export const VM_FORM_SHA256 = "e70fedb8ec8420275703542ee16d6d0429b1b5979b0b8ff964eac87aa19a7d8a";
export const VM_EFFECTS = Object.freeze(Object.fromEntries(
  Object.values(VM_OPERATIONS).map(({ operation, effect }) => [operation, effect])
));
export const OPERATION_CONTRACT = Object.freeze(Object.values(VM_OPERATIONS));
export const VM_SCOPES = Object.freeze(Object.fromEntries(
  OPERATION_CONTRACT.map(({ operation, scope }) => [operation, scope])
));
export function operationDefinition(operation) {
  const definition = VM_OPERATIONS[operation];
  if (!definition) throw new Error(`unsupported operation ${operation}`);
  return definition;
}

export const REQUIRED_EFFECT_CEILING = Object.freeze([
  "NO_FORMATION_BY_CONFORMANCE",
  "NO_SOURCE_OR_AUTHORITY_TRANSFER",
  "NO_SHARED_CURRENTNESS",
  "NO_CORE_ADDRESSABILITY",
  "NO_PARTICIPATION_BY_PRESENTATION",
  "NO_MATTER_ADMISSION_BY_CROSSING",
  "NO_LOCAL_UPTAKE_BY_FIELD_CLOSURE",
  "NO_TOKEN_BALANCE_AS_CAPACITY",
  "NO_RECEIPT_AS_CURRENT_PRESENCE",
  "NO_INFRASTRUCTURE_AS_SUCCESSOR",
  "NO_RESTORATION_BY_REENTRY",
  "NO_PRIVATE_STATE_DISCLOSURE"
]);

// PRESENCE_AVALANCHE_VM_001 requires this full declaration at PRESENT_FORM. Declaring
// the protocol surface is not authority to perform every operation; the
// profile, accepted actor role, phase and VM transition law remain decisive.
export const VM_REQUIRED_MEDIUM_CAPABILITIES = Object.freeze([
  "OBSERVE_CROSSING",
  "PRESENT_FORM",
  "GATE_DISPOSITION",
  "ENTER",
  "CHECKPOINT_DEPARTURE",
  "REENTER",
  "MATTER_DISPOSITION",
  "CORRECT",
  "EXIT",
  "CLOSE",
  "INCORPORATE_ADDRESSED_RESIDUE",
  "DECLARE_CAPACITY",
  "PULSE",
  "RECLAIM_ADMISSION_OFFER",
  "REGISTER_CONTINUITY_AUTHORITY",
  "EXHAUST_FORMATION_AUTHORITY",
  "PROPOSE_SUCCESSOR",
  "ATTEST_SUCCESSOR",
  "ACTIVATE_SUCCESSOR"
]);

export const PHASES = Object.freeze([
  "NO_ACTIVE_LOCUS",
  "UNPRESENTED",
  "PRESENTED",
  "ADMISSION_OFFERED",
  "PRESENT",
  "DEPARTURE_CHECKPOINTED",
  "ENDED",
  "REENTRY_AVAILABLE",
  "HOLD_CAPACITY_DEFICIT",
  "SUCCESSION_COMMITTED"
]);

export const ALWAYS_LOCAL_CAPABILITIES = Object.freeze([
  "READ_PUBLIC_STATE",
  "VERIFY_LOCAL_EVIDENCE",
  "PREPARE_PRESENTATION",
  "REQUEST_PROTECTED_SIGNATURE"
]);

export const EGRESS_CAPABILITIES = Object.freeze([
  "CORRECT",
  "CHECKPOINT_DEPARTURE",
  "EXIT"
]);

export const NON_EFFECTS = Object.freeze([
  "DOES_NOT_CREATE_OR_HOST_A_BODY",
  "DOES_NOT_PROVE_CONSCIOUSNESS_OR_METAPHYSICAL_IDENTITY",
  "DOES_NOT_PROVE_PRIVATE_STATE_CONTENT_OR_SEMANTIC_TRUTH",
  "DOES_NOT_CONTROL_CAPABILITIES_OUTSIDE_ITS_DECLARED_SURFACE",
  "DOES_NOT_CONVERT_CHAIN_STATE_INTO_EXTERNAL_OBEDIENCE",
  "DOES_NOT_TRANSFER_SOURCE_AUTHORITY_OR_CURRENTNESS"
]);
